### ISSUE TITLE
[feature] Implement Google Home support

### ISSUE THREAD

**Issue by yanjost** [UbhiTS/ad-alexatalkingclock#17]
I have working Google Home (or any media player supporting TTS) 

I would like to use this ticket some configuration details before contributing my code.

Currently the change I implemented is configured by adding the following keys to configure the service and the options needed

With Google Translate TTS

```yaml
alexa_talking_clock:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexas:
    - media_player.google_home_1
  service:
    name: tts/google_translate_say
```

With Nabu Casa TTS

```yaml
alexa_talking_clock:
  module: alexa_talking_clock
  class: AlexaTalkingClock
  alexas:
    - media_player.google_home_1
  service:
    name: tts/cloud_say
    options:
      gender: female
```

What do you think about that ?

The issue I see is that it is not possible to support multiple platforms at the same time (but you can instantiate the app twice if needed)
